#!/bin/sh

get_volume_info() {
	if amixer get Master | tail -1 | grep -q "\[on\]"; then
		echo "墳$(amixer get Master | tail -1 | grep -o "[0-9]*%")"
	else
		echo "婢$(amixer get Master | tail -1 | grep -o "[0-9]*%")"
	fi
}

