#!/bin/sh

DWMBAR="$HOME/dwmbar/dwmbar"
delim=" "

source "$DWMBAR/dateandtime"
source "$DWMBAR/audiocontrol"
source "$DWMBAR/internet"

get_status() {
	get_netoperstate
	get_volume
	get_dateandtime
}

while :; do
	xsetroot -name "$(get_status | tr '\n' "$delim")"
	sleep 1m
done
