#!/bin/sh

DWMBAR_PID=$$
readonly DWMBAR_PID
DWMBAR_DIR="$HOME/dwmbar/dwmbar"
DELIMIT=" "

reset_sleep() {
	pkill -P $DWMBAR_PID sleep
}

trap reset_sleep USR1

# source modules
. "$DWMBAR_DIR/dateandtime"
. "$DWMBAR_DIR/audiocontrol"
. "$DWMBAR_DIR/internet"

get_status() {
	get_netoperstate
	get_volume
	get_dateandtime
}

while :; do
	xsetroot -name "$(get_status | tr '\n' "$DELIMIT")"
	sleep 1m &
	wait $!
done

